SOURCE_FOLDER := src
INTERMEDIATE_FOLDER := classes
LIBRARY_FOLDER := lib
BINARY_FOLDER := bin

SOURCE_FILE_SUFFIX := .java
COMPILED_FILE_SUFFIX := .class

SOURCE_FILES = $(addsuffix $(SOURCE_FILE_SUFFIX), $(addprefix $(SOURCE_FOLDER)/, $(SOURCE_FILE_NAMES)))
COMPILED_FILES = $(addsuffix $(COMPILED_FILE_SUFFIX), $(addprefix $(INTERMEDIATE_FOLDER)/, $(SOURCE_FILE_NAMES)))
LIBRARY = $(BINARY_FOLDER)/$(LIBRARY_NAME)


.PHONY: lib
lib: $(LIBRARY)
	
$(LIBRARY): $(COMPILED_FILES)
	jar --create --file $(LIBRARY) -C $(INTERMEDIATE_FOLDER) .
	

$(INTERMEDIATE_FOLDER)/%.class: $(SOURCE_FOLDER)/%.java
	javac $(CLASSPATH) $< -d $(INTERMEDIATE_FOLDER)